### ISSUE TITLE
Quest addon

### ISSUE THREAD

**Issue by JayDee696969** [MetalChris/repository.matrix#3]
Whenever you get a chance, can you check Quest addon. Not working anymore. Im guessing its maybe because the site requires a free login now?

**Comment by MetalChris** [comment]
Looks like some changes to the API are causing the add-on to fail.  I don't think it has anything to do with the site requiring a free login.  They probably just re-arranged some of the info.  I'll look into it further and hopefully have an update in a day or two.

**Comment by MetalChris** [comment]
Just pushed out an update.  The add-on should be working now.  Let me know if you're still having issues.

**Comment by JayDee696969** [comment]
> Just pushed out an update. The add-on should be working now. Let me know if you're still having issues.

Nice, looks good, thanks for the update!!
