### ISSUE TITLE
Fix Repo

### ISSUE THREAD

**Issue by JayDee696969** [MetalChris/repository.matrix#5]
Can you please make a small change to the repo so that it works on Nexus? Just have to ad the dir tag like:
[repository.matrix.zip](https://github.com/MetalChris/repository.matrix/files/10775049/repository.matrix.zip)

**Comment by MetalChris** [comment]
Not sure what you're asking.  You can view the file here:  https://github.com/MetalChris/repository.matrix/blob/main/repository.matrix/addon.xml

**Comment by JayDee696969** [comment]
> Not sure what you're asking. You can view the file here: https://github.com/MetalChris/repository.matrix/blob/main/repository.matrix/addon.xml

Yes, your repo will not work on Nexus because it doesnt have the dir requirements that Nexus now requires. Its hard to type this into the comment. Thats why I posted the zip file with the fix.

**Comment by JayDee696969** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/45118866/220216817-74370e6c-1c76-4abc-bcd5-622039d7e6d3.png)

**Comment by JayDee696969** [comment]
On another note, I was able to fix your CarbonTV addon for Kodi Nexus. xbmc.translatepath is depreciated and now must be xbmcvfs.translatepath. With the repo fix and the translate path fix your addons work fine on Nexus.

**Comment by JayDee696969** [comment]
[plugin.video.carbon-tv.zip](https://github.com/MetalChris/repository.matrix/files/10788561/plugin.video.carbon-tv.zip)

**Comment by MetalChris** [comment]
Ah, ok, a picture is worth a thousand words.  Now I can actually see what you were asking.  Is xbmcvfs.translatepath backwards compatible with Matrix?  I don't want to kill compatibility and have to build a separate repo just for Nexus.

**Comment by JayDee696969** [comment]
> Ah, ok, a picture is worth a thousand words. Now I can actually see what you were asking. Is xbmcvfs.translatepath backwards compatible with Matrix? I don't want to kill compatibility and have to build a separate repo just for Nexus.

Yes, I believe so. Im not using Matrix, but Im pretty sure I tried it. The above carbonTV zip has the Nexus fixes if you want to try it on Matrix.

**Comment by JayDee696969** [comment]
Pretty sure the repo and translatepath fix is backwards compatible.

**Comment by Gujal00** [comment]
>  Is xbmcvfs.translatepath backwards compatible with Matrix? I don't want to kill compatibility and have to build a separate repo just for Nexus.

Kodi 19 onwards translatePath was moved to xbmcvfs module. you can see that used in internetarchive plugin [in line 24](https://github.com/MetalChris/repository.matrix/blob/038f99116f8c549f975db8d06cc95971d93d1dcd/plugin.video.internetarchive/addon.py#L24)

**Comment by MetalChris** [comment]
Working these this weekend.  Thanks for the info and updates.
