### ISSUE TITLE
What happened to the Internet archive video addon 

### ISSUE THREAD

**Issue by Shoninzo** [MetalChris/repository.matrix#7]
I can't find the Internet video archive addon in the latest repo update

**Comment by MetalChris** [comment]
The archive.org website went through some major changes and it broke my addon.  For the first time in over 8 years I was not able to fix it and gave up.  Fear not though, [Gujal00](https://github.com/Gujal00/gujal00.github.io) has taken over maintenance of the addon and brought it back to life.  We can all still enjoy the massive amount of content available!  You can download the [Alpha2 version](https://github.com/Gujal00/gujal00.github.io/raw/master/plugin.video.archive.org-1.0.0~alpha2.zip)   and see more info here: https://forum.kodi.tv/showthread.php?tid=180623&pid=3189415#pid3189415
