### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by newf276** [MetalChris/repository.matrix#8]
Hi, I was wondering is it possible to add the ability to use IPTV Merge form Slyguy to allow for integration with Xumo Addon to load the channels in IPTV Simple client like IPTV Merge does for pluto, samsung, Plex and CBC addons.  If not, thanks for sharing the addons.

**Comment by MetalChris** [comment]
This is a good idea, but unfortunately I'm not very good at this and my coding skills are basic at best.  Matt's code goes way over my head and I'm unable to do this at this time.  Perhaps in the future if I gain a better understanding of how Matt does things I might be able to make this happen.  Thanks for the suggestion. I'll put it on my to-do list.
